Repository nephio-project/test-infra, pull requests merged in 2023-11, with the labels that each got.

#211 Aligning nfdeploy-fn builds to code changes
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#213 Fixing path for images that do not have git installed
  .prow.yaml
Labels: approved, lgtm, kind/cleanup

#214 Pass HTTP proxy environment variables to the Docker daemon
  e2e/provision/playbooks/cluster.yml
Labels: approved, lgtm, ok-to-test, kind/cleanup

#217 Enable add Ansible extra var list
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/cluster.yml
Labels: approved, lgtm, kind/feature
