Repository nephio-project/test-infra, pull requests merged in 2023-10, with the labels that each got.

#194 Expose WebUI port thru Vagrant
  e2e/provision/Vagrantfile
Labels: approved, lgtm

#183 Enable `main` nephio packages version in periodic prow jobs
  .prow.yaml
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/install/README.md
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/terraform/main.tf
  e2e/terraform/modules/gcp/main.tf
  e2e/terraform/modules/gcp/variables.tf
Labels: approved, lgtm

#196 Fix for molecule image build
  images/molecule/Dockerfile
Labels: approved, lgtm

#197 Fix permissions during molecule execution
  images/molecule/Dockerfile
Labels: approved, lgtm, kind/bug

#198 Use root as value for USER env var into molecule Docker image
  images/molecule/Dockerfile
Labels: approved, lgtm, kind/bug

#199 Use nephio molecule docker image in prow
  .prow.yaml
Labels: approved, lgtm, kind/cleanup, kind/feature

#186 Upgrade gtp5G kernel module
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/tests/007.sh
  e2e/tests/009.sh
Labels: approved, lgtm

#200 Enable Dockerfile linter tool
  .prow.yaml
  images/e2e/Dockerfile
  images/generic-autobumper/Dockerfile
  images/label_sync/Dockerfile
Labels: approved, lgtm, kind/cleanup

#201 Fix python version in e2e image
  images/e2e/Dockerfile
Labels: approved, lgtm, kind/bug

#204 Moving periodics from inrepoconfig to main
  .prow.yaml
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#202 Adding OAI images build
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#205 Fix periodic prow periodic tasks
  .prow.yaml
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#206 Add extra_refs in prow periodic jobs
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#207 Enabling inrepoconfig for OAI
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#208 Adding path alias in extra_refs and changing execution path
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#209 Nephio Experimental configuration
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, kind/feature

#210 Enabling Prow for whole Nephio Experimental
  prow/config/config.yaml
  prow/config/plugins.yaml
Labels: approved, lgtm, kind/feature
