Repository nephio-project/test-infra, pull requests merged in 2023-06, with the labels that each got.

#58 Fix to ssh in as ubuntu
  e2e/provision/README.md
Labels: approved, lgtm

#60 Use sysctl Ansible module
  e2e/provision/Vagrantfile
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/system-setup.yml
  e2e/terraform/main.tf
Labels: approved, lgtm

#61 Next steps on e2e after creating workload clusters
  e2e/provision/README.md
  e2e/provision/free5gc-cp-1.png
  e2e/provision/free5gc-cp-2.png
  e2e/provision/free5gc-cp-3.png
Labels: approved, lgtm

#64 enabling lifecycle plugin
  prow/config/plugins.yaml
Labels: approved, lgtm

#63 Initial start of e2e tests
  e2e/e2e.sh
  e2e/lib/k8s.sh
  e2e/lib/testing.sh
  e2e/provision/README.md
  e2e/provision/gce_init.sh
  e2e/provision/gce_install_sandbox.sh
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/terraform/main.tf
  e2e/tests/000.sh
  e2e/tests/001.sh
  e2e/tests/002-edge-clusters.yaml
  e2e/tests/002.sh
  e2e/tests/003.sh
  e2e/tests/004-free5gc-operator.yaml
  e2e/tests/005-regional-free5gc-amf.yaml
  e2e/tests/005-regional-free5gc-smf.yaml
  e2e/tests/006-edge-free5gc-upf.yaml
Labels: approved, lgtm

#67 Update images and associated README contents for regional free5gc-cp
  e2e/provision/README.md
  e2e/provision/free5gc-cp-1.png
  e2e/provision/free5gc-cp-2.png
  e2e/provision/free5gc-cp-3.png
  e2e/provision/free5gc-cp-4.png
  e2e/provision/free5gc-cp-5.png
  e2e/provision/free5gc-cp-6.png
Labels: approved, lgtm

#69 Add regional label
  e2e/provision/README.md
Labels: approved, lgtm

#68 Enable the Free5GC operator to be deployed on all workload clusters
  e2e/tests/004-free5gc-operator.yaml
Labels: approved, lgtm, ok-to-test

#65 Proposal to reuse e2e and lab terraform scripts
  e2e/provision/gce_install_sandbox.sh
  e2e/terraform/main.tf
  e2e/terraform/output.tf
  e2e/terraform/variables.tf
Labels: approved, lgtm

#54 Builds for homebrewed images
  .prow.yaml
  images/label_sync/Dockerfile
Labels: approved

#73 Vagrant Sandbox provisioning support for Windows
  e2e/provision/Vagrantfile
Labels: approved, lgtm, ok-to-test

#75 Improve editorial description
  e2e/provision/README.md
Labels: lgtm, needs-ok-to-test

#62 free5gc artifact name update
  prow/config/config.yaml
Labels: approved, lgtm

#77 Activate changes in Docker group
  e2e/provision/gce_init.sh
Labels: approved, lgtm, ok-to-test

#76 Use v3 of the free5gc operator package
  e2e/tests/004-free5gc-operator.yaml
  e2e/tests/004.sh
Labels: approved, lgtm

#79 Correct test-name and packagevariant name
  e2e/tests/006.sh
Labels: approved, lgtm, ok-to-test

#78 Update to latest nephio-controllers, nephio-workload-cluster packages
  e2e/launch.sh
  e2e/provision/bash_config.sh
  e2e/provision/gce_init.sh
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/tests/001.sh
  e2e/tests/002-edge-clusters.yaml
  e2e/tests/002.sh
  e2e/tests/004.sh
  e2e/tests/005.sh
  e2e/tests/006.sh
Labels: approved, lgtm

#81 Add 007 ueransim test.
  e2e/lib/k8s.sh
  e2e/tests/007-edge-free5gc-ueransim.yaml
  e2e/tests/007.sh
Labels: approved, lgtm

#84 Deploy network package for IPAM config
  e2e/launch.sh
  e2e/provision/gce_install_sandbox.sh
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/tests/005-regional-free5gc-amf.yaml
  e2e/tests/005-regional-free5gc-smf.yaml
  e2e/tests/006-edge-free5gc-upf.yaml
Labels: approved

#74 Adding generic-autobumper image for prow updater
  .prow.yaml
  images/generic-autobumper/Dockerfile
Labels: approved, lgtm

#82 Updated init script to allow metadata override
  e2e/provision/README.md
  e2e/provision/gce_init.sh
  e2e/provision/hacks/resolve_secrets.sh
Labels: approved, lgtm

#89 Update to resource-backend/v2
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
Labels: approved

#85 Improve documentation format
  e2e/provision/README.md
Labels: approved, lgtm

#91 Provide default reconcile timeout value
  e2e/provision/gce_install_sandbox.sh
  e2e/provision/playbooks/roles/kpt/defaults/main.yml
  e2e/provision/playbooks/roles/kpt/tasks/main.yml
Labels: approved, lgtm

#90 Add resource backend config
  e2e/provision/README.md
  e2e/tests/003-network-topo.yaml
  e2e/tests/003.sh
Labels: approved

#92 Fix bash scripts format
  e2e/e2e.sh
  e2e/launch.sh
  e2e/lib/k8s.sh
  e2e/lib/testing.sh
  e2e/provision/bash_config.sh
  e2e/provision/gce_init.sh
  e2e/provision/gce_install_sandbox.sh
  e2e/provision/hacks/resolve_secrets.sh
  e2e/tests/000.sh
  e2e/tests/001.sh
  e2e/tests/002.sh
  e2e/tests/003.sh
  e2e/tests/004.sh
  e2e/tests/005.sh
  e2e/tests/006.sh
  e2e/tests/007.sh
Labels: approved, lgtm

#94 Have the user deploy the network package
  e2e/provision/README.md
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/tests/000.sh
  e2e/tests/001.sh
  e2e/tests/002.sh
  e2e/tests/003-network.yaml
  e2e/tests/003.sh
  e2e/tests/004.sh
  e2e/tests/005.sh
  e2e/tests/006.sh
  e2e/tests/007.sh
Labels: approved, do-not-merge/hold

#96 fixed paths for new context
  prow/config/config.yaml
Labels: approved, lgtm

#88 Enabling MPL license in lichen conf
  images/gotests/lichen.yaml
Labels: approved, lgtm

#95 Minor corrections
  e2e/provision/README.md
Labels: approved, lgtm, ok-to-test

#97 Remove gce_* prefix
  .prow.yaml
  e2e/launch.sh
  e2e/provision/README.md
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/terraform/main.tf
Labels: approved, lgtm

#99 Reduce delay time since fixes make them unnecessary
  e2e/tests/005-regional-free5gc-amf.yaml
  e2e/tests/005-regional-free5gc-smf.yaml
  e2e/tests/006-edge-free5gc-upf.yaml
Labels: approved

#102 add CLA plugin
  prow/config/plugins.yaml
Labels: approved, lgtm

#101 Add reconcile timeout flag to non-ansible instructions
  e2e/provision/hacks/resolve_secrets.sh
  e2e/provision/install_sandbox.sh
Labels: approved, lgtm

#103 Updated README.md for VM installs
  e2e/provision/README.md
Labels: approved, lgtm

#104 Drop python3-virtualenv dependency
  e2e/provision/install_sandbox.sh
Labels: approved, lgtm

#100 Add test step interconnect clusters
  .gitignore
  e2e/provision/README.md
  e2e/provision/playbooks/cluster.yml
  e2e/tests/002-topo.gotmpl
  e2e/tests/002.sh
Labels: approved, lgtm

#80 008.sh UPF Capacity Scaling
  e2e/tests/008.sh
Labels: approved, lgtm, ok-to-test, cncf-cla: no

#98 Import the bash gtp5g installation into Ansible role
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-20.yml
  e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-22.yml
Labels: approved, lgtm

#108 Fix deployment names and namespaces for AMF, SMF
  e2e/tests/005.sh
Labels: approved, lgtm

#109 Import kpt bash instructions in Ansible
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/library/kpt.py
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/kpt/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/tasks/wait_deployments.yml
Labels: approved, lgtm

#110 Force Ansible handlers
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
Labels: approved, lgtm

#112 Fixed Dockerfile name for nad-fn
  prow/config/config.yaml
Labels: approved, lgtm

#107 Create repository settings
  .gitattributes
Labels: approved, lgtm

#114 Bump andrewrothstein.kpt version to 0.0.3
  e2e/provision/galaxy-requirements.yml
Labels: approved, lgtm

#93 Use init.sh bash script as main starting point
  .prow.yaml
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/terraform/main.tf
  e2e/terraform/variables.tf
Labels: approved, lgtm, ok-to-test

#115 Improve interconnect template
  e2e/lib/k8s.sh
  e2e/lib/testing.sh
  e2e/tests/002-topo.gotmpl
  e2e/tests/002.sh
  e2e/tests/008.sh
Labels: approved, lgtm

#113 moving lichen scan logic to script
  images/gotests/Dockerfile
  images/gotests/lichen.sh
Labels: approved, lgtm

#116 Allow nephio home to be configured on install
  e2e/provision/README.md
  e2e/provision/init.sh
Labels: approved, lgtm

#118 Improve Bootstrap ansible role
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/prechecks.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/system-setup.yml
  e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-20.yml
  e2e/provision/playbooks/roles/bootstrap/vars/ubuntu-22.yml
Labels: approved, lgtm

#117 Version bumps in gotests adding lichen bin
  images/gotests/Dockerfile
Labels: approved, lgtm

#119 Align Network topology values
  e2e/provision/README.md
  e2e/tests/002.sh
  e2e/tests/003-network-topo.yaml
Labels: approved, lgtm

#106 Fix install molecule test
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/install/README.md
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/install/molecule/default/tests/test_default.py
Labels: approved, lgtm

#105 Import kubeconfig creation into Ansible Role
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/install/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/molecule/default/molecule.yml
  e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/kpt/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/kpt/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/tasks/wait_deployments.yml
Labels: approved, lgtm

#121 Enable Google vagrant provider
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
Labels: approved, lgtm

#122 counting from 1
  e2e/tests/002-topo.gotmpl
  e2e/tests/002.sh
  e2e/tests/003-network-topo.yaml
Labels: approved, lgtm

#124 net-config
  e2e/tests/003-network-topo.tmpl
  e2e/tests/003-secret.yaml
  e2e/tests/003.sh
Labels: approved, lgtm

#126 adding configinject-fn
  prow/config/config.yaml
Labels: approved, lgtm

#127 Enabling building all images in nephio in the same time
  prow/config/config.yaml
Labels: approved, lgtm

#128 Removing specializer-operator
  prow/config/config.yaml
Labels: approved, lgtm

#111 008.sh extended to check if UPF Scale Succeeded
  e2e/tests/008.sh
Labels: approved, lgtm, ok-to-test

#130 Remove free5gc reference from UERANSIM deployment
  e2e/tests/007-edge-ueransim.yaml
  e2e/tests/007.sh
Labels: approved, lgtm

#129 Modifications based on live testing
  e2e/tests/008.sh
Labels: approved, lgtm

#131 Improve errors information
  e2e/lib/k8s.sh
  e2e/lib/testing.sh
  e2e/provision/init.sh
Labels: approved, lgtm

#132 updates README to reflect the correct file extension for 003-network-topo
  e2e/provision/README.md
  e2e/provision/hacks/network-topo.sh
Labels: approved, lgtm

#133 Ansible refactoring
  e2e/lib/testing.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/bootstrap/vars/redhat.yml
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/tests/000.sh
Labels: approved, lgtm

#135 Add a subscriber with curl
  e2e/tests/007-edge-ueransim.yaml
  e2e/tests/007-edge01-ueransim.yaml
  e2e/tests/007-subscriber.json
  e2e/tests/007.sh
Labels: approved, lgtm

#136 008.sh corrects the metrics check
  e2e/tests/008.sh
Labels: approved, lgtm, ok-to-test

#139 Do not use interactive terminal mode for exec
  e2e/lib/k8s.sh
Labels: approved, lgtm

#140 Redirect to docs repo
  e2e/provision/README.md
  e2e/provision/free5gc-cp-1.png
  e2e/provision/free5gc-cp-2.png
  e2e/provision/free5gc-cp-3.png
  e2e/provision/free5gc-cp-4.png
  e2e/provision/free5gc-cp-5.png
  e2e/provision/free5gc-cp-6.png
Labels: approved

#141 008.sh - moved scale check to lib and handle mCPU and Integer Cores
  e2e/lib/k8s.sh
  e2e/tests/008.sh
Labels: approved, lgtm, needs-ok-to-test

#142 Fix kubeconfig name
  e2e/tests/008.sh
Labels: approved

#143 One more fix
  e2e/tests/008.sh
Labels: approved

#138 Add a conditional validation for uesimtun0 network interfaces
  e2e/tests/007.sh
Labels: approved, lgtm

#137 009.sh to test vertical scaling of SMF capacity based on maxSessions and maxNFConnections
  e2e/tests/009.sh
Labels: approved, ok-to-test

#145 Increase the e2e timeout to 1h15m
  .prow.yaml
Labels: approved, lgtm

#144 make fmt
  e2e/lib/k8s.sh
  e2e/tests/007.sh
  e2e/tests/008.sh
  e2e/tests/009.sh
Labels: approved

#148 Fix unbound var
  e2e/provision/hacks/network-topo.sh
  e2e/tests/003.sh
Labels: approved

#150 Reractoring functions
  e2e/lib/k8s.sh
  e2e/provision/hacks/inter-connect_workers.sh
  e2e/provision/init.sh
  e2e/tests/001.sh
  e2e/tests/002.sh
  e2e/tests/003.sh
  e2e/tests/008.sh
  e2e/tests/009.sh
  images/gotests/lichen.sh
Labels: approved, lgtm

#151 Improve Ansible performance
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/requirements.in
  e2e/provision/requirements.txt
Labels: approved, lgtm

#153 Use unambiguous resource for CAPI cluster objects
  e2e/tests/001.sh
  e2e/tests/002.sh
Labels: approved, lgtm

#154 Adding ueransim-deploy-fn
  prow/config/config.yaml
Labels: approved, lgtm
