Repository nephio-project/test-infra, pull requests merged in 2024-10, with the labels that each got.

#308 Adding ansible galaxy install pre_task to deploy_kubeadm_k8s
  e2e/provision/playbooks/deploy_kubeadm_k8s.yml
Labels: approved, lgtm, kind/bug

#298 Make sandbox install script WSL-friendly
  e2e/provision/install_sandbox.sh
  images/generic-autobumper/Dockerfile
  images/gotests/Dockerfile
  images/label_sync/Dockerfile
  images/releaser/Dockerfile
Labels: approved, lgtm, kind/feature

#306 Script output logging for e2e tests
  e2e/lib/testing.sh
Labels: approved, lgtm, kind/design

#311 Disabling 009 free5gc testcase
  e2e/tests/free5gc/disable-009.sh.BAK
Labels: approved, lgtm, kind/failing-test

#303 Upgrade k8s version v1.30.0
  e2e/provision/galaxy-requirements.yml
  e2e/provision/init.sh
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml
Labels: approved, lgtm, kind/cleanup

#312 Force packer to replace existing image
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug
