Repository nephio-project/test-infra, pull requests merged in 2024-08, with the labels that each got.

#291 Increased waiting time to sign image for longer builds than 10 minute…
  .prow.yaml
  images/releaser/release.sh
Labels: approved, lgtm, kind/bug

#292 Bumping curl version
  images/releaser/Dockerfile
Labels: approved, lgtm, kind/cleanup

#293 Set explicit inventory parameters while installing porch
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/tasks/main.yml
Labels: approved, lgtm, kind/feature

#294 Delete a Dockerhub secret before attempting to create on during init
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
Labels: approved, lgtm, kind/feature

#296 add support for installing nonKIND cluster via kubeadm (previously PR #46)
  e2e/provision/playbooks/deploy_kubeadm_k8s.yml
  e2e/provision/playbooks/roles/kubeadm/defaults/main.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/kubeadm-Debian.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/kubeadm-RedHat.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/main.yml
Labels: approved, lgtm, kind/feature

#297 adds prow job to install nephio components on kubeadm cluster
  .prow.yaml
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/deploy_kubeadm_k8s.yml
  e2e/provision/playbooks/roles/kubeadm/defaults/main.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/kubeadm-Debian.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/kubeadm-RedHat.yml
  e2e/provision/playbooks/roles/kubeadm/tasks/main.yml
  e2e/terraform/main.tf
  e2e/terraform/modules/gcp/main.tf
  e2e/terraform/modules/gcp/variables.tf
Labels: approved, lgtm, kind/feature

#299 Adding ok-to-test label for Prow
  tools/dependabot/generate_dependabot.py
Labels: approved, lgtm, kind/cleanup

#300 Remove nephio docker dev build jobs
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup
