Repository nephio-project/test-infra, pull requests merged in 2024-01, with the labels that each got.

#229 Update the list of Nephio stocks repositories
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/prep-gitea.yml
  e2e/provision/playbooks/roles/install/README.md
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/provision/playbooks/roles/install/molecule/default/tests/test_default.py
  e2e/provision/playbooks/roles/install/tasks/main.yml
  e2e/provision/playbooks/roles/kpt/README.md
  e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/upgrade/README.md
  e2e/provision/playbooks/roles/upgrade/molecule/default/prepare.yml
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/001.sh
  e2e/tests/oai/002-oai-operators.yaml
  e2e/tests/oai/003-upf.yaml
  e2e/tests/oai/003.sh
Labels: approved, lgtm

#227 Adding OAI RAN and UE test deployment scripts
  e2e/tests/oai/002-oai-operators.yaml
  e2e/tests/oai/002.sh
  e2e/tests/oai/004-ran-cucp.yaml
  e2e/tests/oai/004.sh
  e2e/tests/oai/005.sh
Labels: approved, lgtm, ok-to-test

#215 Adding go coverage reporting
  images/gotests/Dockerfile
  images/gotests/coverage.sh
Labels: approved, lgtm, kind/feature

#231 Updating the location of files
  e2e/tests/oai/001-infra.sh
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-dependency.sh
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.sh
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004-ran-network.sh
  e2e/tests/oai/004-ran-network.yaml
  e2e/tests/oai/005-ue.sh
  e2e/tests/oai/005-ue.yaml
  e2e/tests/oai/006-end-to-end-call.sh
Labels: approved, lgtm, kind/cleanup

#230 Enable `fail fast` CI feature to reduce the End-to-End testing consumption
  .prow.yaml
  e2e/lib/kpt.sh
  e2e/lib/porch.sh
  e2e/provision/Vagrantfile
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/terraform/main.tf
  e2e/terraform/modules/gcp/main.tf
  e2e/terraform/modules/gcp/variables.tf
  e2e/tests/free5gc/004.sh
  e2e/tests/free5gc/005.sh
  e2e/tests/free5gc/006.sh
  e2e/tests/free5gc/007.sh
  e2e/tests/oai/004-ran-network.sh
  e2e/tests/oai/005-ue.sh
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature
