Repository nephio-project/test-infra, pull requests merged in 2024-06, with the labels that each got.

#267 Add logs for wait end times and porch package approval times to e2e tests
  e2e/lib/k8s.sh
  e2e/lib/kpt.sh
  e2e/lib/porch.sh
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/008.sh
  e2e/tests/free5gc/009.sh
  e2e/tests/oai/001b-infra-metal-lb.sh
Labels: approved, lgtm, kind/cleanup

#268 Script for extracting timestamped entries from e2e test logs
  e2e/lib/log2timestampcsv.py
Labels: approved, lgtm, kind/cleanup

#266 feat: Automate released image signing
  .prow.yaml
  images/releaser/Dockerfile
  images/releaser/release.sh
  prow/config/config.yaml
Labels: approved, lgtm, ok-to-test, kind/feature

#271 Fix Ansible linting issues
  e2e/provision/init.sh
  e2e/provision/playbooks/cluster.yml
Labels: approved, lgtm, kind/bug

#273 Add Liam to approvers list
  OWNERS
Labels: approved, lgtm

#274 Upgrade dependencies
  e2e/provision/galaxy-requirements.yml
  e2e/provision/requirements.txt
  e2e/provision/test-requirements.txt
Labels: approved, lgtm, kind/cleanup

#275 adding the apache requests library
  e2e/provision/test-requirements.in
  e2e/provision/test-requirements.txt
Labels: approved, lgtm

#276 Revert "Update Dockerfile - version bump."
  images/molecule/Dockerfile
Labels: approved, lgtm

#277 Bumping openssh-client version to unbroke build after the revert of 276
  images/molecule/Dockerfile
Labels: approved, lgtm

#272 Switching e2e tests to run on main
  e2e/defaults.env
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/004-ran-network.yaml
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm, kind/failing-test

#269 adds support in scripts for deploying nephio components on real K8S(non-kind)
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
Labels: approved, lgtm
