Repository nephio-project/test-infra, pull requests merged in 2024-07, with the labels that each got.

#279 fix: Add latest tag for releaser image
  .prow.yaml
Labels: approved, lgtm, ok-to-test

#281 Fix porch release images builds
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#286 Fixing sandbox unbound variable error
  e2e/provision/install_sandbox.sh
Labels: approved, lgtm

#282 Switching e2e tests to v3.0.0
  e2e/defaults.env
  e2e/provision/galaxy-requirements.yml
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/terraform/modules/gcp/main.tf
  e2e/terraform/modules/gcp/variables.tf
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/004.sh
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/005.sh
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/006.sh
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/free5gc/007.sh
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/001b-infra-metal-lb.sh
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.sh
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004-ran-network.sh
  e2e/tests/oai/004-ran-network.yaml
  e2e/tests/oai/005-ue.sh
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm, kind/feature

#284 Automated signing fixes and improvements
  images/releaser/release.sh
Labels: approved, lgtm, kind/cleanup

#288 Fixing image autosign - prow part
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#289 Removing invalidcommitmsg plugin
  prow/config/plugins.yaml
Labels: approved, lgtm, kind/cleanup

#287 Switching back to main
  e2e/defaults.env
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004-ran-network.yaml
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm, kind/cleanup

#290 Upgrading lichen to version with better license detection
  images/gotests/Dockerfile
Labels: approved, lgtm, kind/failing-test
