Repository nephio-project/test-infra, pull requests merged in 2024-04, with the labels that each got.

#254 Cleanup and update
  e2e/provision/Vagrantfile
  e2e/provision/galaxy-requirements.yml
  e2e/provision/init.sh
  e2e/provision/nephio.yaml
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/kpt/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/upgrade/molecule/default/prepare.yml
  e2e/provision/requirements.in
  e2e/provision/requirements.txt
Labels: approved, lgtm, kind/cleanup

#251 add support for OAI e2e tests for fedora34
  .prow.yaml
Labels: approved, lgtm

#256 Fixing token path
  e2e/packer/gcp/main.pkr.hcl
Labels: approved, lgtm, kind/bug

#257 Add Fedora 34 OAI Periodic to Config
  prow/config/config.yaml
Labels: approved, lgtm, ok-to-test, kind/feature

#258 Update gotests to Go 1.22
  images/gotests/Dockerfile
Labels: approved, lgtm, kind/design

#259 Updating gotests binaries
  images/gotests/Dockerfile
Labels: approved, lgtm, kind/failing-test

#261 Upgrade gtp5g version and enable verifiers
  e2e/e2e.sh
  e2e/provision/init.sh
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/load-gtp5g-module.yml
Labels: approved, lgtm, kind/feature
