Repository nephio-project/test-infra, pull requests merged in 2024-02, with the labels that each got.

#232 Fix one-liner bash Sandbox install
  e2e/provision/init.sh
  e2e/provision/playbooks/roles/bootstrap/README.md
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/ci/molecule.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/main.yml
  e2e/provision/playbooks/roles/bootstrap/tasks/prechecks.yml
Labels: approved, lgtm, kind/feature

#233 Removing watcher-agent and nf-deploy-controler
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#234 Enable periodic task execution for OAI End-to-End testing
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#235 Separating metal-lb ip-address pool definition
  e2e/tests/oai/001a-infra.sh
  e2e/tests/oai/001b-infra-metal-lb.sh
Labels: approved, lgtm

#238 Adding porch release images builds
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#237 Update documentation link references
  e2e/provision/README.md
Labels: approved, lgtm, kind/bug

#240 Update references to v2.0.0 revision
  e2e/defaults.env
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/001b-infra-metal-lb.sh
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/004-ran-network.yaml
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm, kind/feature

#241 Adding a label for stock repos to be visible in external blueprints
  e2e/provision/playbooks/roles/install/tasks/main.yml
Labels: approved, lgtm

#242 Adding release automation script
  tools/release/config.json
  tools/release/kraken.py
  tools/release/requirements.txt
  tools/release/util.py
Labels: approved, lgtm, kind/feature

#243 Add porchctl bin to sandbox install
  e2e/provision/playbooks/cluster.yml
Labels: approved, lgtm

#244 Update kpt alpha to use porchctl
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/008.sh
  e2e/tests/free5gc/009.sh
  e2e/tests/oai/001b-infra-metal-lb.sh
Labels: approved, lgtm, kind/feature

#245 Fix for latest tag in commit image builds for OAI
  prow/config/config.yaml
Labels: approved, lgtm, kind/bug

#246 Remove ones-22 config
  .prow.yaml
  e2e/README.md
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/terraform/modules/gcp/main.tf
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#247 Improve logging process
  e2e/lib/_assertions.sh
  e2e/lib/k8s.sh
  e2e/lib/kpt.sh
  e2e/lib/porch.sh
  e2e/provision/init.sh
  e2e/provision/install_sandbox.sh
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/004.sh
  e2e/tests/free5gc/005.sh
  e2e/tests/free5gc/006.sh
  e2e/tests/oai/001a-infra.sh
  e2e/tests/oai/001b-infra-metal-lb.sh
  e2e/tests/oai/003-core-network.sh
  e2e/tests/oai/004-ran-network.sh
  e2e/tests/oai/005-ue.sh
  images/gotests/coverage.sh
  tools/release/tag-catalog-packages.sh
Labels: approved, lgtm, kind/feature
