Repository nephio-project/test-infra, pull requests merged in 2025-07, with the labels that each got.

#355 ArgoCD e2e Test
  .prow.yaml
  e2e/tests/argocd/001.sh
  e2e/tests/argocd/002-free5gc-cp.yaml
  e2e/tests/argocd/002.sh
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#354 Upgrade tools and platform
  .gitignore
  e2e/provision/init.sh
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/ci/molecule.yml
  e2e/provision/playbooks/roles/bootstrap/molecule/default/prepare.yml
  e2e/provision/playbooks/roles/install/molecule/ci/molecule.yml
  e2e/provision/requirements.in
  e2e/provision/requirements.txt
  e2e/provision/test-requirements.in
  e2e/provision/test-requirements.txt
  e2e/tests/flux/001.sh
Labels: approved, lgtm, kind/failing-test

#358 Update weekly jobs to run at 2am
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#359 Remove git branch log assertions
  e2e/tests/argocd/001.sh
  e2e/tests/flux/001.sh
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/003.sh
  e2e/tests/oai/001b-infra-metal-lb.sh
  e2e/tests/ocloud/001.sh
Labels: approved, lgtm, kind/cleanup
