Repository nephio-project/test-infra, pull requests merged in 2025-02, with the labels that each got.

#320 Add fluxcd workload suite
  .prow.yaml
  e2e/lib/capi.sh
  e2e/tests/flux/001.sh
  e2e/tests/flux/002-free5gc-cp.yaml
  e2e/tests/flux/002.sh
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#322 O2 IMS Operator release image build
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#324 Add release job for focom oper image
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#323 O2IMS e2e Test
  .prow.yaml
  e2e/tests/o2ims/001-sample-provisioning-request.yaml
  e2e/tests/o2ims/001.sh
Labels: approved, lgtm, kind/feature

#325 Fixing image build paths for new operators
  prow/config/config.yaml
Labels: approved, lgtm, kind/cleanup

#326 Quick fix operators
  prow/config/config.yaml
Labels: approved, lgtm

#327 Another operator fix
  prow/config/config.yaml
Labels: approved, lgtm

#328 Switching test-infra to v4.0.0
  e2e/defaults.env
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/tests/flux/002-free5gc-cp.yaml
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/o2ims/001-sample-provisioning-request.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004a-ran-network.yaml
  e2e/tests/oai/004b-ran-network.yaml
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm

#329 Switching back to main
  e2e/defaults.env
  e2e/provision/playbooks/cluster.yml
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/provision/playbooks/roles/install/defaults/main.yml
  e2e/tests/flux/002-free5gc-cp.yaml
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/o2ims/001-sample-provisioning-request.yaml
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004a-ran-network.yaml
  e2e/tests/oai/004b-ran-network.yaml
  e2e/tests/oai/005-ue.yaml
Labels: approved, lgtm

#330 add missing license headers
  images/e2e/Dockerfile
  images/generic-autobumper/Dockerfile
  images/gotests/Dockerfile
  images/gotests/checklicense.sh
  images/label_sync/Dockerfile
  images/linter/Dockerfile
  images/molecule/Dockerfile
  images/releaser/Dockerfile
  tools/release/tag-catalog-packages.sh
Labels: approved, lgtm, needs-ok-to-test
