Repository nephio-project/test-infra, pull requests merged in 2025-05, with the labels that each got.

#334 Bump gotest image versions
  images/gotests/Dockerfile
Labels: approved, lgtm, kind/failing-test

#336 Add tide config to automatically squash merged PRs
  prow/config/config.yaml
Labels: approved, lgtm

#337 Fix tox provision-linter
  e2e/.gitignore
  e2e/provision/tox.ini
Labels: approved, kind/failing-test

#332 Update tests for integer revision handling
  .prow.yaml
  README.md
  e2e/README.md
  e2e/defaults.env
  e2e/lib/capi.sh
  e2e/lib/porch.sh
  e2e/provision/playbooks/roles/bootstrap/defaults/main.yml
  e2e/tests/flux/001.sh
  e2e/tests/flux/002-free5gc-cp.yaml
  e2e/tests/flux/002.sh
  e2e/tests/free5gc/001.sh
  e2e/tests/free5gc/002-edge-clusters.yaml
  e2e/tests/free5gc/002-network.yaml
  e2e/tests/free5gc/003.sh
  e2e/tests/free5gc/004-free5gc-operator.yaml
  e2e/tests/free5gc/004.sh
  e2e/tests/free5gc/005-edge-free5gc-upf.yaml
  e2e/tests/free5gc/005.sh
  e2e/tests/free5gc/006-regional-free5gc-amf.yaml
  e2e/tests/free5gc/006-regional-free5gc-smf.yaml
  e2e/tests/free5gc/006.sh
  e2e/tests/free5gc/007-edge01-ueransim.yaml
  e2e/tests/free5gc/007.sh
  e2e/tests/free5gc/008.sh
  e2e/tests/o2ims/001-sample-provisioning-request.yaml
  e2e/tests/o2ims/001.sh
  e2e/tests/oai/001-infra.yaml
  e2e/tests/oai/001-network.yaml
  e2e/tests/oai/001b-infra-metal-lb.sh
  e2e/tests/oai/002-database.yaml
  e2e/tests/oai/002-operators.yaml
  e2e/tests/oai/003-core-network.sh
  e2e/tests/oai/003-core-network.yaml
  e2e/tests/oai/004a-ran-network.sh
  e2e/tests/oai/004a-ran-network.yaml
  e2e/tests/oai/004b-ran-network.sh
  e2e/tests/oai/004b-ran-network.yaml
  e2e/tests/oai/005-ue.sh
  e2e/tests/oai/005-ue.yaml
  images/gotests/coverage.sh
  prow/config/config.yaml
Labels: do-not-merge/work-in-progress

#331 Add ocloud e2e
  .prow.yaml
  e2e/terraform/modules/gcp/main.tf
  e2e/tests/o2ims/001-sample-provisioning-request.yaml
  e2e/tests/ocloud/001-focom-provisioning-request.yaml
  e2e/tests/ocloud/001.sh
  prow/config/config.yaml
Labels: approved, lgtm, kind/feature

#340 Add packer presubmit job and tidy
  .prow.yaml
  e2e/packer/gcp/main.pkr.hcl
  prow/config/config.yaml
Labels: enhancement, approved, lgtm, kind/failing-test
